version: '3.8'

services:
  app:
    build: .
    container_name: discord_bot
    depends_on:
      - mongo
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
